upstream flask_backend {
    server backend:5000;
}

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location /shorten {
        proxy_pass http://flask_backend;
        proxy_set_header Host $host;
    }

    location /health {
        proxy_pass http://flask_backend;
    }

    location / {
        try_files $uri @backend;
    }

    location @backend {
        proxy_pass http://flask_backend;
        proxy_set_header Host $host;
    }
}
